name: python V2rayCollector Script

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure Git
        run: |
          git config --global user.email "tahmasebimoein140@gmail.com"
          git config --global user.name "tahmaseb73"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4

      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py  # Replace with your script's path
          git add -A
          git commit -m "The servers have been updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git pull --rebase origin main
          git push
